version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=310106
      - APP_USER=RM565468
      - APP_USER_PASSWORD=310106
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./init-db:/container-entrypoint-initdb.d
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 3m

  patinhasemdia-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patinhasemdia-api
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__OracleConnection=User Id=RM565468;Password=310106;Data Source=oracle-db:1521/XEPDB1;
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      oracle-db:
        condition: service_healthy
    restart: always

volumes:
  oracle_data:
    name: oracle_persistence_volume
